# -*- coding: utf-8 -*-
"""HW0223

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4cx9LlgfIMrPadzhkp9FJlFm8hjZBXL
"""

import numpy as np
import matplotlib.pyplot as plt

p = 0.3
n = 50
num_samples = 10000

# Generate sample means
sample_means = [
    np.mean(np.random.binomial(1, p, n))
    for _ in range(num_samples)
]

# Standardize
sample_means = np.array(sample_means)

standardized = (sample_means - p) / np.sqrt(p * (1 - p) / n)

# Plot
plt.hist(standardized, bins=50, density=True)
plt.title("CLT for Bernoulli Distribution")
plt.xlabel("Standardized Sample Mean")
plt.ylabel("Density")
plt.show()